#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_tools.goals.linters import DEFAULT_PYTHON
NAME = "test_docker_module"
BACKEND = "docker"

LINT = [
    *DEFAULT_PYTHON,
]
TEST = []
DEPLOY = []
