#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_build.goals.linters import DEFAULT_PYTHON


path = pathlib.Path(__file__).parent

NAME = "test_docker_module"
BACKEND = "docker"

LINT = [
    *DEFAULT_PYTHON,
]
TEST = []
DEPLOY = []
