#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_tools.goals.linters import DEFAULT_TERRAFORM


NAME = "example_terraform"
BACKEND = "system"

LINT = [
    *DEFAULT_TERRAFORM,
]
TEST = []
DEPLOY = []
