#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_tools.goals.linters import DEFAULT_DOCKER, DEFAULT_PYTHON

NAME = "example_docker_module"
BACKEND = "docker"

LINT = [
    *DEFAULT_PYTHON,
    # *DEFAULT_DOCKER,
]
TEST = []
DEPLOY = []
