#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_tools.goals.linters import DEFAULT_PYTHON
from py_mono_tools.goals.tester import PytestTester
from py_mono_tools.goals.deployers import PoetryBuilder


NAME = "py_mono_tools"
BACKEND = "system"

LINT = [
    *DEFAULT_PYTHON,
]
TEST = [PytestTester(test_dir="../../test/py_mono_tools")]
DEPLOY = [PoetryBuilder(pyproject_loc="../../pyproject.toml")]
