#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_build.goals.linters import (
    Bandit,
    Black,
    DocStringFormatter,
    Flake8,
    ISort,
    Mypy,
    Pydocstyle,
    Pylint,
)


path = pathlib.Path(__file__).parent

NAME = "py_mono_build"

LINT = [
    Bandit(),
    Black(),
    DocStringFormatter(),
    Flake8(),
    ISort(),
    Mypy(),
    Pydocstyle(),
    Pylint(),
    # TFSec(),
    # CheckOV(),
    # Terrascan( args=["-d", "./terraform"]),
    # TFLint( args=["./terraform/services/aws/modules/networking"]),
]
TEST = []
DEPLOY = []
