#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_tools.goals.linters import (  # DEFAULT_PYTHON,; DEFAULT_TERRAFORM,
    Bandit,
    Black,
    CheckOV,
    Flake8,
    ISort,
    Mypy,
    PyDocStringFormatter,
    Pydocstyle,
    Pylint,
    TerrascanTerraform,
    TFLint,
    TFSec,
)


path = pathlib.Path(__file__).parent

NAME = "<EXAMPLE>"
BACKEND = "<docker,system>"

# You can list each linter or use one of the default linter lists.
# NOTE: ORDER DOES MATTER!
# LINT = [*DEFAULT_PYTHON, *DEFAULT_TERRAFORM]
LINT = [
    Bandit(),
    Black(),
    PyDocStringFormatter(),
    Flake8(),
    ISort(),
    Mypy(),
    Pydocstyle(),
    Pylint(),
    TFSec(),
    CheckOV(),
    TerrascanTerraform(args=["-d", "./terraform"]),
    TFLint(args=["./terraform/services/aws/modules/networking"]),
]
TEST = []
DEPLOY = []
