#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_tools.goals.linters import DEFAULT_TERRAFORM


path = pathlib.Path(__file__).parent

NAME = "py_mono_tools"
BACKEND = "system"

LINT = [
    *DEFAULT_TERRAFORM,
]
TEST = []
DEPLOY = []
