#!/user/bin/env python
# -*- coding: utf-8 -*-
import pathlib

from py_mono_tools.goals.linters import DEFAULT_PYTHON


NAME = "example_system_module"
BACKEND = "system"

LINT = [
    *DEFAULT_PYTHON,
]
TEST = []
DEPLOY = []
